org: ivanrodriguezperez
service: api-alumnos

provider:
  name: aws
  runtime: python3.12
  timeout: 30  
  iam:
    role: arn:aws:iam::748213590633:role/LabRole

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "tenant_id": "$input.json('$.tenant_id')"
                }

  crear:
    handler: CrearAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/crear
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "tenant_id": "$input.json('$.tenant_id')",
                  "alumno_id": "$input.json('$.alumno_id')",
                  "alumno_datos": $input.json('$.alumno_datos')
                }

  modificar:
    handler: ModificarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/modificar
          method: put
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "tenant_id": "$input.json('$.tenant_id')",
                  "alumno_id": "$input.json('$.alumno_id')",
                  "alumno_datos": $input.json('$.alumno_datos')
                }

  eliminar:
    handler: EliminarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/eliminar
          method: delete
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "tenant_id": "$input.json('$.tenant_id')",
                  "alumno_id": "$input.json('$.alumno_id')"
                }

  buscar:
    handler: BuscarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/buscar
          method: post
          cors: true
          integration: lambda
          request:
            template:
              application/json: |
                {
                  "tenant_id": "$input.json('$.tenant_id')",
                  "alumno_id": "$input.json('$.alumno_id')"
                }
